apiVersion: v1
kind: Service
metadata: 
  name: app-deploy-service
  labels:
    name: app-deploy
    app: app-deploy
    namespace: prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    name: app-deploy-pod
    app: app-deploy