---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: service-a@gpt-j-and-gpt-neox20b.iam.gserviceaccount.com
#   name: service-a
#   namespace: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcloud
  template:
    metadata:
      labels:
        app: gcloud
    spec:
      # serviceAccountName: service-a
      containers:
      - name: cloud-sdk
        image: google/cloud-sdk:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleeep 30; done;" ]
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: iam.gke.io/gke-metadata-server-enabled
      #           operator: In
      #           values:
      #             - "true"